version: '3'
services:
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=adminpassword
      - MONGODB_DATABASE=urlshortener
      - MONGODB_USERNAME=urluser
      - MONGODB_PASSWORD=urlpassword
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 80:8080
    environment:
      - BACKEND_DB_DATABASE=urlshortener
      - BACKEND_DB_USERNAME=urluser
      - BACKEND_DB_PASSWORD=urlpassword
    networks:
      - app-network

networks:
  app-network:
    external: true
